services:
  db:
    image: postgres:18-alpine
    container_name: postgresql
    restart: always

    ports:
      - "0.0.0.0:5432:5432"

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: den
      POSTGRES_PASSWORD: gocapdulu

    volumes:
      - postgresql_db:/var/lib/postgresql/data

volumes:
  postgresql_db:
    driver: local
