---
- name: Get Device Running Configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Run show running-config
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: Save configuration to file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ playbook_dir }}/../../configs/{{ inventory_hostname }}.cfg"
