---
- name: Push Cisco Configuration
  hosts: all
  gather_facts: false
  vars:
    interface_config: {}
  tasks:
    - name: Apply configuration commands
      cisco.ios.ios_config:
        parents: "{{ interface_config.name | default(omit) }}"
        lines: "{{ interface_config.commands }}"